import { type Metadata } from 'next'
import './globals.css'
import ThemeProvider from '@/providers/ThemeProvider';
import ClientOnly from '@/components/ClientOnly/ClientOnly';
import { NotificationProvider } from '@/providers/Notification';

export const metadata: Metadata = {
  title: 'Herbalism - Admin',
  description: 'Generated by create next app',
  applicationName: 'Herbalism - Admin',
  keywords: ["react", "server components", 'nextjs', 'tailwind', 'admin', 'dashboard'],
  icons: [
    { rel: "favicon", type: 'image/ico', url: "/favicon.ico" }
  ],
  generator: 'khoadev',
  authors: [{ name: 'khoadev' }],
  creator: 'khoadev'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="vi">
      <body className="min-h-screen flex flex-col">
        <ClientOnly>
          <NotificationProvider>
            <main className="flex-1">{children}</main>
          </NotificationProvider>
        </ClientOnly>
      </body>
    </html>

  )
}
